### ISSUE TITLE
Fond image des (simili)-boutons

### ISSUE THREAD

**Issue by franck-paul** [access42/AccessConfig#2]
Dans le cas où une des options de contraste (inversion ou renforcement) est activée il serait peut-être opportun d'annuler les images (propriété CSS background-image) utilisées en fond de boutons, voire des éléments inputs, puisque ces images remplacent la couleur de fond positionnée par la CSS d'AccessConfig

**Comment by franck-paul** [comment]
En y réfléchissant, je me dis que c'est peut-être too much, certains boutons utilisant une image de fond à la place du texte, du coup je ne sais pas trop ce qu'il faut en faire de ce ticket :-)

Un avis les experts a11y ?

**Comment by franck-paul** [comment]
Pour info, pour l'application sur l'administration d'un blog Dotclear j'ai opté pour un masquage des images de fond et je gère le hover/focus avec une règle CSS comme suit :

```css
button, .simili-button {
  background-image: none;
}
button:hover, .simili-button:hover,
button:focus, .simili-button:focus {
  filter: invert(100%);
}
```
